### ISSUE TITLE
Porting the functionalities when bugs happen

### ISSUE THREAD

**Issue by harikt** [harikt/cake-migrations#1]
What will be the good way to port the functionality when bugs happen. 

Currently if cake can keep some of the functionalities without cakephp dependency we could have used the package.

@lorenzo do you have any thoughts on this ?

Thank you

**Comment by lorenzo** [comment]
I was thinking that this is a good prototype for offering the cakephp/migrations package also as a standalone. I'll discuss the idea with the others

**Comment by harikt** [comment]
Thank you @lorenzo .

I think the same approach can be used with the other functionalities. 

Eg : `bin/cake bake migration AddNameIndexToProducts name:string:index`

But it may take some time for me to understand first how these works.

**Comment by harikt** [comment]
Hey @lorenzo forget to ask you, whether you got any feedback regarding this.

Thank you.

**Comment by lorenzo** [comment]
No, sorry. I promise I will get something on this tomorrow :)

**Comment by harikt** [comment]
no problem. Just wanted to know ie all. 

Thank you.

**Comment by harikt** [comment]
@lorenzo ping :) .
